name = "QuantumControlBase"
uuid = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>"]
version = "0.0.1"

[deps]
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"

[compat]
QuantumPropagators = "^0.0"
julia = "1.6"
