name = "QuantumControlBase"
uuid = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>"]
version = "0.0.1"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"

[compat]
ConcreteStructs = "0.2"
QuantumPropagators = "^0.0"
julia = "1.6"
