name = "QuantumControlBase"
uuid = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>"]
version = "0.0.3+dev"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "^0.25"
DrWatson = "2"
QuantumPropagators = "^0.0"
julia = "1.6"
