name = "QuantumControlBase"
uuid = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
authors = ["Michael Goerz <mail@michaelgoerz.net>", "Alastair Marshall <alastair@nvision-imaging.com>"]
version = "0.0.1"

[compat]
julia = "1.6"
