name = "QuantumControlBase"
uuid = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.11.0"

[deps]

[weakdeps]

[extensions]

[compat]
julia = "1.9"
